os: osx
osx_image: xcode11.4
language: swift

before_install:
  - gem install xcpretty

script:
  - set -o pipefail
  - |
    xcodebuild \
    -project coffeebrew46.xcodeproj \
    -scheme coffeebrew46 \
    -destination "platform=iOS Simulator,OS=13.4,name=iPhone 8" \
    -sdk iphonesimulator test | xcpretty -c
