attributes:
  LastSwiftUpdateCheck: '1140'
  LastUpgradeCheck: '1140'
configs:
  Debug: debug
  Release: release
name: BrewCoffee46
options:
  defaultConfig: Release
  groupSortPosition: bottom
  transitivelyLinkDependencies: false
  useBaseInternationalization: false
packages:
  SwiftUITooltip:
    url: https://github.com/quassum/SwiftUI-Tooltip.git
    from: 1.4.0
  Factory:
    url: https://github.com/hmlongco/Factory.git
    from: 2.3.2
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 11.2.0
  SwiftJWT:
    url: https://github.com/Kitura/Swift-JWT.git
    from: 4.0.2
  BrewCoffee46Core:
    path: BrewCoffee46Core
settings:
  base:
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
    DEAD_CODE_STRIPPING: YES
    ENABLE_USER_SCRIPT_SANDBOXING: NO
    MARKETING_VERSION: 2.4.0
    CURRENT_PROJECT_VERSION: 2.4.0
    SWIFT_VERSION: '6.0.3'
    MTL_FAST_MATH: 'YES'
    SWIFT_STRICT_CONCURRENCY: 'complete'
    DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
  configs:
    Debug:
      MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
      ONLY_ACTIVE_ARCH: YES
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      SWIFT_OPTIMIZATION_LEVEL: -Onone
      GCC_OPTIMIZATION_LEVEL: 0
    Release:
      MTL_ENABLE_DEBUG_INFO: NO
      SWIFT_OPTIMIZATION_LEVEL: -Owholemodule
targets:
  brewcoffee46:
    platform: iOS
    productName: BrewCoffee46
    deploymentTarget: 
      iOS: 17.0
    settings:
      base:
        IPHONEOS_DEPLOYMENT_TARGET: 17.0
        SDKROOT: iphoneos
        INFOPLIST_FILE: BrewCoffee46/Info.plist
        CODE_SIGN_IDENTITY: Apple Development
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: BrewCoffee46/brewcoffee46.entitlements
        DEVELOPMENT_ASSET_PATHS: '"BrewCoffee46/Preview Content"'
        DEVELOPMENT_TEAM: 3KDN4W8346
        PRODUCT_NAME: BrewCoffee46
        PROVISIONING_PROFILE_SPECIFIER: ''
        CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
        OTHER_LDFLAGS:
          - $(inherited)
          - -ObjC
      configs:
        Debug:
          PRODUCT_BUNDLE_IDENTIFIER: com.github.y-yu.coffeebrew46.debug
        Release:
          PRODUCT_BUNDLE_IDENTIFIER: com.github.y-yu.coffeebrew46
    sources:
      - BrewCoffee46
      - Localizable
    dependencies:
      - target: brewcoffee46WatchKitApp
      - package: BrewCoffee46Core
        product: BrewCoffee46Core
      - package: SwiftUITooltip
      - package: Factory
      - package: SwiftJWT
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseCrashlytics
    type: application
    preBuildScripts:
      - script: |
          if [ $CONFIGURATION = "Debug" ]; then
            if [ "${CI}" != "true" ]; then
              source ${PROJECT_DIR}/.envrc
            fi
            /usr/bin/env xcrun --sdk macosx swift build --disable-sandbox -c release --product license-plist
            ${PROJECT_DIR}/.build/release/license-plist --output-path ${PROJECT_DIR}/${PRODUCT_NAME}/Settings.bundle --github-token $LICENSE_PLIST_GITHUB_TOKEN
          fi
        name: Run license-plist
        outputFiles:
          - ${PROJECT_DIR}/.build/release/license-plist
          - ${PROJECT_DIR}/${PRODUCT_NAME}/Settings.bundle
    postBuildScripts:
      - script: |
          if [ "${CI}" == "true" ]; then
            cp "${PROJECT_DIR}/${PRODUCT_NAME}/config/GoogleService-Info-CI.plist" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/GoogleService-Info.plist"            
          elif [ "${CONFIGURATION}" == "Release" ]; then
            cp "${PROJECT_DIR}/${PRODUCT_NAME}/config/GoogleService-Info-Release.plist" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/GoogleService-Info.plist"
          else
            cp "${PROJECT_DIR}/${PRODUCT_NAME}/config/GoogleService-Info-Debug.plist" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/GoogleService-Info.plist"
          fi
        name: Generate GoogleService-Info.plist
        outputFiles:
          - $(BUILT_PRODUCTS_DIR)/$(PRODUCT_NAME).app/GoogleService-Info.plist
      - script: ${BUILD_DIR%/Build/*}/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run
        name: Crashlytics run
        inputFiles:
          - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}
          - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${PRODUCT_NAME}
          - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Info.plist
          - $(TARGET_BUILD_DIR)/$(UNLOCALIZED_RESOURCES_FOLDER_PATH)/GoogleService-Info.plist
          - $(TARGET_BUILD_DIR)/$(EXECUTABLE_PATH)
        basedOnDependencyAnalysis: false

  brewcoffee46Tests:
    platform: iOS
    productName: BrewCoffee46Tests
    settings:
      base:
        IPHONEOS_DEPLOYMENT_TARGET: 17.0
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
        BUNDLE_LOADER: $(TEST_HOST)
        CODE_SIGN_IDENTITY[sdk=macosx*]: '-'
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: ''
        INFOPLIST_FILE: BrewCoffee46Tests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.github.y-yu.coffeebrew46Tests
        PROVISIONING_PROFILE_SPECIFIER: ''
        PROVISIONING_PROFILE_SPECIFIER[sdk=macosx*]: ''
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/BrewCoffee46.app/BrewCoffee46
    sources:
      - BrewCoffee46Tests
    dependencies:
      - target: brewcoffee46
      - package: BrewCoffee46Core
        product: BrewCoffee46TestsShared
    type: bundle.unit-test

  brewcoffee46WatchKitApp:
    platform: watchOS
    deploymentTarget: 
      watchOS: 10.4
    productName: BrewCoffee46WatchKitApp
    settings:
      base:
        WATCHOS_DEPLOYMENT_TARGET: 10.4
        CODE_SIGN_IDENTITY: Apple Development
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_ASSET_PATHS: '"BrewCoffee46WatchKitApp/Preview Content"'
        INFOPLIST_FILE: 'BrewCoffee46WatchKitApp/Info.plist'
        DEVELOPMENT_TEAM: 3KDN4W8346
        PRODUCT_NAME: BrewCoffee46WatchKitApp
        PROVISIONING_PROFILE_SPECIFIER: ''
        CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
        OTHER_LDFLAGS:
          - $(inherited)
          - $(OTHER_LDFLAGS)
      configs:
        Debug:
          PRODUCT_COMPANION_APP_BUNDLE_IDENTIFIER: com.github.y-yu.coffeebrew46.debug
          PRODUCT_BUNDLE_IDENTIFIER: com.github.y-yu.coffeebrew46.debug.watchkitapp
        Release:
          PRODUCT_COMPANION_APP_BUNDLE_IDENTIFIER: com.github.y-yu.coffeebrew46
          PRODUCT_BUNDLE_IDENTIFIER: com.github.y-yu.coffeebrew46.watchkitapp
    sources:
      - BrewCoffee46WatchKitApp
      - Localizable
    dependencies:
      - package: BrewCoffee46Core
        product: BrewCoffee46Core
      - package: Factory
    type: application

schemes:
  brewcoffee46:
    build:
      targets:
        brewcoffee46: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - brewcoffee46
      targets:
        - name: brewcoffee46Tests
          parallelizable: true
          randomExecutionOrder: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  brewcoffee46WatchKitApp:
    build:
      targets:
        brewcoffee46WatchKitApp: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
