attributes:
  LastSwiftUpdateCheck: '1140'
  LastUpgradeCheck: '1140'
configs:
  Debug: debug
  Release: release
name: BrewCoffee46
options:
  defaultConfig: Release
  groupSortPosition: bottom
  transitivelyLinkDependencies: false
  useBaseInternationalization: false
packages:
  SwiftUITooltip:
    url: https://github.com/quassum/SwiftUI-Tooltip.git
    from: 1.4.0
  Factory:
    url: https://github.com/hmlongco/Factory.git
    from: 2.3.1
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 10.25.0
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
  configs:
    Debug:
      MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
      MTL_FAST_MATH: 'YES'
      SDKROOT: iphoneos
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      SWIFT_OPTIMIZATION_LEVEL: -Onone
    Release:
      MTL_FAST_MATH: 'YES'
      SDKROOT: iphoneos
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: -O
targets:
  brewcoffee46:
    platform: iOS
    productName: BrewCoffee46
    settings:
      base:
        INFOPLIST_FILE: brewcoffee46/Info.plist
        DEVELOPMENT_TEAM: 3KDN4W8346
      configs:
        Debug:
          CODE_SIGN_IDENTITY: Apple Development
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_ASSET_PATHS: '"brewcoffee46/Preview Content"'
          PRODUCT_BUNDLE_IDENTIFIER: com.github.y-yu.coffeebrew46.debug
          PRODUCT_NAME: BrewCoffee46
          PROVISIONING_PROFILE_SPECIFIER: ''
          CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
        Release:
          CODE_SIGN_IDENTITY: Apple Development
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_ASSET_PATHS: '"brewcoffee46/Preview Content"'
          PRODUCT_BUNDLE_IDENTIFIER: com.github.y-yu.coffeebrew46
          PRODUCT_NAME: BrewCoffee46
          PROVISIONING_PROFILE_SPECIFIER: ''
          CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
    sources:
    - path: brewcoffee46
      name: brewcoffee46
    dependencies:
      - package: SwiftUITooltip
      - package: Factory
      - package: Firebase
        product: FirebaseAnalytics
    type: application
    postBuildScripts:
      - script: |
          if [ "${CI}" == "true" ]; then
            cp "${PROJECT_DIR}/${PROJECT_NAME}/config/GoogleService-Info-CI.plist" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/GoogleService-Info.plist"            
          elif [ "${CONFIGURATION}" == "Release" ]; then
            cp "${PROJECT_DIR}/${PROJECT_NAME}/config/GoogleService-Info-Release.plist" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/GoogleService-Info.plist"
          else
            cp "${PROJECT_DIR}/${PROJECT_NAME}/config/GoogleService-Info-Debug.plist" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/GoogleService-Info.plist"
          fi
        name: Generate GoogleService-Info.plist
        outputFiles:
          - $(BUILT_PRODUCTS_DIR)/$(PRODUCT_NAME).app/GoogleService-Info.plist
  brewcoffee46Tests:
    dependencies:
    - target: brewcoffee46
    platform: iOS
    productName: BrewCoffee46Tests
    settings:
      configs:
        Debug:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
          BUNDLE_LOADER: $(TEST_HOST)
          CODE_SIGN_IDENTITY[sdk=macosx*]: '-'
          CODE_SIGN_STYLE: Manual
          DEVELOPMENT_TEAM: ''
          INFOPLIST_FILE: brewcoffee46Tests/Info.plist
          PRODUCT_BUNDLE_IDENTIFIER: com.github.y-yu.coffeebrew46Tests
          PROVISIONING_PROFILE_SPECIFIER: ''
          PROVISIONING_PROFILE_SPECIFIER[sdk=macosx*]: ''
          SWIFT_VERSION: '5.0'
          TEST_HOST: $(BUILT_PRODUCTS_DIR)/BrewCoffee46.app/BrewCoffee46
        Release:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
          BUNDLE_LOADER: $(TEST_HOST)
          CODE_SIGN_IDENTITY[sdk=macosx*]: '-'
          CODE_SIGN_STYLE: Manual
          DEVELOPMENT_TEAM: ''
          INFOPLIST_FILE: brewcoffee46Tests/Info.plist
          PRODUCT_BUNDLE_IDENTIFIER: com.github.y-yu.coffeebrew46Tests
          PROVISIONING_PROFILE_SPECIFIER: ''
          PROVISIONING_PROFILE_SPECIFIER[sdk=macosx*]: ''
          SWIFT_VERSION: '5.0'
          TEST_HOST: $(BUILT_PRODUCTS_DIR)/BrewCoffee46.app/BrewCoffee46
    sources:
    - path: brewcoffee46Tests
      name: brewcoffee46Tests
    type: bundle.unit-test
