attributes:
  LastSwiftUpdateCheck: '1140'
  LastUpgradeCheck: '1140'
configs:
  Debug: debug
  Release: release
name: CoffeeBrew46
options:
  defaultConfig: Release
  groupSortPosition: bottom
  transitivelyLinkDependencies: false
  useBaseInternationalization: false
packages:
  SwiftUITooltip:
    url: https://github.com/quassum/SwiftUI-Tooltip.git
    from: 1.4.0
  Factory:
    url: https://github.com/hmlongco/Factory.git
    from: 2.3.1
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
  configs:
    Debug:
      MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
      MTL_FAST_MATH: 'YES'
      SDKROOT: iphoneos
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      SWIFT_OPTIMIZATION_LEVEL: -Onone
    Release:
      MTL_FAST_MATH: 'YES'
      SDKROOT: iphoneos
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: -O
targets:
  coffeebrew46:
    platform: iOS
    productName: CoffeeBrew46
    settings:
      base:
        INFOPLIST_FILE: coffeebrew46/Info.plist
        DEVELOPMENT_TEAM: 3KDN4W8346
      configs:
        Debug:
          CODE_SIGN_IDENTITY: Apple Development
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_ASSET_PATHS: '"coffeebrew46/Preview Content"'
          PRODUCT_BUNDLE_IDENTIFIER: com.github.y-yu.coffeebrew46.debug
          PRODUCT_NAME: CoffeeBrew46
          PROVISIONING_PROFILE_SPECIFIER: ''
        Release:
          CODE_SIGN_IDENTITY: Apple Development
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_ASSET_PATHS: '"coffeebrew46/Preview Content"'
          PRODUCT_BUNDLE_IDENTIFIER: com.github.y-yu.coffeebrew46
          PRODUCT_NAME: CoffeeBrew46
          PROVISIONING_PROFILE_SPECIFIER: ''
    sources:
    - path: coffeebrew46
      name: coffeebrew46
    dependencies:
      - package: SwiftUITooltip
      - package: Factory
    type: application
  coffeebrew46Tests:
    dependencies:
    - target: coffeebrew46
    platform: iOS
    productName: CoffeeBrew46Tests
    settings:
      configs:
        Debug:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
          BUNDLE_LOADER: $(TEST_HOST)
          CODE_SIGN_IDENTITY[sdk=macosx*]: '-'
          CODE_SIGN_STYLE: Manual
          DEVELOPMENT_TEAM: ''
          INFOPLIST_FILE: coffeebrew46Tests/Info.plist
          PRODUCT_BUNDLE_IDENTIFIER: com.github.y-yu.coffeebrew46Tests
          PROVISIONING_PROFILE_SPECIFIER: ''
          PROVISIONING_PROFILE_SPECIFIER[sdk=macosx*]: ''
          SWIFT_VERSION: '5.0'
          TEST_HOST: $(BUILT_PRODUCTS_DIR)/CoffeeBrew46.app/CoffeeBrew46
        Release:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
          BUNDLE_LOADER: $(TEST_HOST)
          CODE_SIGN_IDENTITY[sdk=macosx*]: '-'
          CODE_SIGN_STYLE: Manual
          DEVELOPMENT_TEAM: ''
          INFOPLIST_FILE: coffeebrew46Tests/Info.plist
          PRODUCT_BUNDLE_IDENTIFIER: com.github.y-yu.coffeebrew46Tests
          PROVISIONING_PROFILE_SPECIFIER: ''
          PROVISIONING_PROFILE_SPECIFIER[sdk=macosx*]: ''
          SWIFT_VERSION: '5.0'
          TEST_HOST: $(BUILT_PRODUCTS_DIR)/CoffeeBrew46.app/CoffeeBrew46
    sources:
    - path: coffeebrew46Tests
      name: coffeebrew46Tests
    type: bundle.unit-test
